### ISSUE TITLE
In the same model, why should these four data sets be trained together?

### ISSUE THREAD

**Issue by wpumain** [AggMan96/RK-Net#7]
https://github.com/AggMan96/RK-Net/blob/14356dae2bfa81c154fcb5c14ea1cf0a75a61ff9/train.py#L199

`
for data,data2,data3,data4 in zip(dataloaders['satellite'], dataloaders['street'], dataloaders['drone'], dataloaders['google']) :`
In this model, it also extracts the image features of these four data sets separately. Why should we train them together?

**Comment by AggMan96** [comment]
Thank you for interesting in our work.
In our model, we use a shared classifier to map features from different views to the same feature space. Training all data together can reduce the bias of feature space to a certain view. Hope this reply can help you.

**Comment by wpumain** [comment]
Think you for your help!
